[".asdf"]
  type = "archive"
  url = "https://github.com/asdf-vm/asdf/archive/refs/tags/v0.9.0.tar.gz"
  stripComponents = 1

[".local/share/nvim/site/autoload/plug.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
